app/biaset/biaset/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('', include('core.urls')),
    path('admin/doc/',include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')), # Django-Allauth URLs

]

app/biaset/core/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .views import HomeView, ShowCaseView, RegolamentoView

urlpatterns = [
    path('', ShowCaseView.as_view(), name='index'),
    path('regolamento/', RegolamentoView.as_view(),name='regolamento'),
    path('dashboard/', login_required(HomeView.as_view()), name='dashboard_index'),
    path('gestioneutenza/', include(('gestioneutenza.urls', 'gestioneutenza'), namespace='gestioneutenza')),
    path('gestionecampionato/', include(('gestionecampionato.urls', 'gestionecampionato'), namespace='gestionecampionato')),
    path('gestionesquadra/', include(('gestionesquadra.urls', 'gestionesquadra'), namespace='gestionesquadra')),
]

app/biaset/gestionecampionato/urls.py
from django.urls import path, include
from .views import CreaCampionatoView, InserisciRiserveView, ModificaCampionatoView, VisualizzaPartitaView, \
    GeneraCalendarioView, SelezionaModuloView, InserisciFormazioneTitolariView, VisualizzaCalendarioView, \
    CaricamentoVotiView, CreaCampionatoLAView
from django.contrib.auth.decorators import login_required

app_name = 'gestionecampionato'

urlpatterns = [
    path('creacampionato/', login_required(CreaCampionatoView.as_view()), name='inserisci_campionato'),
    path('creacampionato/la/', login_required(CreaCampionatoLAView.as_view()), name='inserisci_campionato_la'),
    path('modificacampionato/<pk>/', login_required(ModificaCampionatoView.as_view()), name='modifica_campionato'),
    path('generacalendario/', login_required(GeneraCalendarioView.as_view()), name='genera_calendario'),
    path('inserisciformazione/', login_required(SelezionaModuloView.as_view()), name='seleziona_modulo'),
    path('inserisciformazione/titolari/<int:d>/<int:c>/<int:a>/',
         login_required(InserisciFormazioneTitolariView.as_view()), name='inserisci_titolari'),
    path('inserisciformazione/riserve/', login_required(InserisciRiserveView.as_view()), name='inserisci_riserve'),
    path('calendario/list/', login_required(VisualizzaCalendarioView.as_view()), name='visualizza_calendario'),
    path('visualizzapartita/<giornata>/<squadra_id>/', login_required(VisualizzaPartitaView.as_view()),
         name='visualizza_partita'),
    path('caricamentovoti/', login_required(CaricamentoVotiView.as_view()), name='caricamento_voti')
]

app/biaset/gestionesquadra/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import VisualizzaSquadraView, AssociaGiocatoreASquadra, licenziaGiocatore, InserisciSquadraView, \
    VisualizzaSquadreLAView, ModificaNomeSquadraView, ModificaSquadraView, eliminaSquadra

app_name = 'gestionesquadra'
urlpatterns = [
    path('visualizzasquadra/<int:pk>/', login_required(VisualizzaSquadraView.as_view()), name='visualizza_squadra'),
    path('ajax/licenziagiocatore/', login_required(licenziaGiocatore), name='licenzia_giocatore_ajax'),
    path('ajax/eliminasquadra/', login_required(eliminaSquadra), name='elimina_squadra_ajax'),
    path('associagiocatore/', login_required(AssociaGiocatoreASquadra.as_view()), name='associa_giocatore'),
    path('inseriscisquadra/', login_required(InserisciSquadraView.as_view()), name='inserisci_squadra'),
    path('modificanomesquadra/<pk>/', login_required(ModificaNomeSquadraView.as_view()), name='modifica_squadra'),
    path('modificasquadra/<pk>/', login_required(ModificaSquadraView.as_view()), name='modifica_squadra_superuser'),
    path('list/', login_required(VisualizzaSquadreLAView.as_view()), name='visualizza_squadre'),
]

app/biaset/gestioneutenza/urls.py
from django.urls import path
from gestioneutenza.views import RegistrationView, StrategyRegistrationView, LoginView, InviteCreateView, LogoutView, ListUtentiView
from django.contrib.auth.decorators import login_required

app_name = 'gestioneutenza'
urlpatterns = [
    path('registrazione/', login_required(RegistrationView.as_view()), name='registrazione'),
    path('registrazione/<str:regtype>/', login_required(StrategyRegistrationView.as_view()), name='registrazione_ca'),
    path('login/', LoginView.as_view(), name='login_view'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('creainvito/', InviteCreateView.as_view(), name='crea_invito'),
    path('utenti/', login_required(ListUtentiView.as_view()), name='list_utenti')
]

app/biaset/templates/front/includes/base/header.html
{% load static %}
{% block header %}
			<header class="header">
				<div class="logo-container">
					<a href="{% url 'dashboard_index' %}" class="logo">
						<img src="{% static 'assets/images/logo_fca.png' %}" height="45" alt="V" />
					</a>
					<div class="visible-xs toggle-sidebar-left" data-toggle-class="sidebar-left-opened" data-target="html" data-fire-event="sidebar-left-opened">
						<i class="fa fa-bars" aria-label="Toggle sidebar"></i>
					</div>
				</div>
			
				<!-- start: user box -->
				<div class="header-right">
					<span class="separator"></span>
					<div id="userbox" class="userbox">
						<a href="#" data-toggle="dropdown">
							<figure class="profile-picture">
								<img src="{% static 'assets/images/!logged-user.jpg' %}" alt="Joseph Doe" class="img-circle" data-lock-picture="assets/images/!logged-user.jpg" />
							</figure>
							<div class="profile-info" data-lock-name="{{ user.first_name }} {{ user.last_name }}">
								<span class="name">{{ user.first_name }} {{ user.last_name }} </span>
								<span class="role">{{ request.session.profilo }}</span>
							</div>
			
							<i class="fa custom-caret"></i>
						</a>
			
						<div class="dropdown-menu">
							<ul class="list-unstyled">
								<li class="divider"></li>
								<li>
									<a role="menuitem" tabindex="-1" href="#"><i class="fa fa-user"></i> Il mio profilo</a>
								</li>
								<li>
									<a role="menuitem" tabindex="-1" href="{% url 'gestioneutenza:logout' %}"><i class="fa fa-power-off"></i> Logout</a>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<!-- end: user box -->
            </header>
{% endblock %}

app/biaset/templates/front/includes/base/menu-campionato.html
{% block menucampionato %}
<li class="nav-parent">
    <a>
        <i class="fa fa-trophy" aria-hidden="true"></i>
        <span>Gestione campionato</span>
    </a>
    <ul class="nav nav-children">
            {% if request.session.squadra_id %}
        <li>
            <a href="{% url 'gestionecampionato:seleziona_modulo' %}">
                 Inserisci/modifica formazione
            </a>
        </li>
        <li>
            <a href="{% url 'gestionecampionato:visualizza_partita' request.session.giornata_corrente request.session.squadra_id%}">
                 Visualizza partita corrente
            </a>
        </li>
        {% endif %}
    {% if request.session.profilo != 'League Admin' %}
        <li>
            <a href="{% url 'gestionecampionato:visualizza_calendario' %}">
                 Visualizza calendario scontri
            </a>
        </li>
    {% endif %}
        {% if request.session.profilo == 'Championship Admin' and request.session.campionato_id %}
        <li>
            <a href="{% url 'gestionecampionato:modifica_campionato' request.session.campionato_id %}">
                 Modifica nome campionato
            </a>
        </li>
        <li>
            <a href="{% url 'gestionecampionato:genera_calendario' %}">
                 Genera calendario scontri
            </a>
        </li>
         <li>
            <a href="{% url 'gestionecampionato:caricamento_voti' %}">
                 Caricamento voti
            </a>
        </li>
        {% endif %}

        {% if request.session.profilo == 'League Admin'%}
        <li>
            <a href="http://localhost:8000/admin/gestionecampionato/campionato/">
                 Visualizza tutti i campionati
            </a>
        </li>
        <li>
            <a href="">
                 Inserisci campionato
            </a>
        </li>
        {% endif %}
    </ul>
</li>
{% endblock %} 

app/biaset/templates/front/includes/base/menu-squadra.html
{% block menusquadra %}
									<!-- Gestione Squadra -->
									<li class="nav-parent">
										<a>
											<i class="fa fa-futbol" aria-hidden="true"></i>
											<span>Gestione Squadra</span>
										</a>
										<ul class="nav nav-children">
                                        {% if request.session.squadra_id %}
											<li>
												<a href="{% url 'gestionesquadra:visualizza_squadra' request.session.squadra_id %}">
													 Visualizza squadra
												</a>
											</li>
											<li>
												<a href="{% url 'gestionesquadra:modifica_squadra' request.session.squadra_id %}">
													 Modifica nome squadra
												</a>
											</li>
                                        {% endif %}
                                            {% if request.session.profilo == 'Championship Admin'%}
											<li>
												<a href="{% url 'gestionesquadra:inserisci_squadra' %}">
													 Inserisci squadra al campionato
												</a>
											</li>
											<li>
												<a href="{% url 'gestionesquadra:associa_giocatore' %}">
													 Associa giocatore a squadra
												</a>
											</li>
                                            {% endif %}

                                            {% if request.session.profilo == 'League Admin'%}
											<li>
												<a href="{% url 'gestionesquadra:inserisci_squadra' %}">
													 Inserisci squadra
												</a>
											</li>
											<li>
												<a href="{% url 'gestionesquadra:visualizza_squadre' %}">
													 Visualizza squadre
												</a>
											</li>
                                            {% endif %}
										</ul>
									</li>
{% endblock %}

app/biaset/templates/front/includes/base/menu-utenza.html
{% block menuutenza %}
<li class="nav-parent">
    <a>
        <i class="fa fa-user" aria-hidden="true"></i>
        <span>Gestione utenza</span>
    </a>
    <ul class="nav nav-children">
        <li>
            <a href="">
                 Il tuo profilo
            </a>
        </li>
        {% if request.session.profilo == 'Championship Admin'%}
        <li>
            <a href="{% url 'gestioneutenza:list_utenti' %}?type=campionato">
                 Visualizza utenti campionato
            </a>
        </li>
        <li>
            <a href="{% url 'gestioneutenza:crea_invito' %}">
                 Invita utente
            </a>
        </li>                          
        {% endif %}

        {% if request.session.profilo == 'League Admin'%}
        <li>
            <a href="http://localhost:8000/admin/auth/user/">
                 Visualizza utenti piattaforma
            </a>
        </li>   
        {% endif %}
    </ul>
</li>
{% endblock %}

app/biaset/templates/front/includes/base/messages.html
{% block content%}

    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    {% if messages %}
    <script>
        {% for message in messages %}
             Swal.fire({
                        position: 'top-center',
                        icon: '{{message.tags}}',
                        title: '{{message}}',
                        showConfirmButton: false,
                        timer: 3000
                        });
        {% endfor %}
    </script>
    {% endif %}

{% endblock %}

app/biaset/templates/front/includes/base/sidebar-left.html
{% block sidebar %}
				<aside id="sidebar-left" class="sidebar-left">
				
					<div class="sidebar-header">
						<div class="sidebar-toggle hidden-xs" data-toggle-class="sidebar-left-collapsed" data-target="html" data-fire-event="sidebar-left-toggle">
							<i class="fa fa-bars" aria-label="Toggle sidebar"></i>
						</div>
					</div>
				
					<div class="nano">
						<div class="nano-content">
							<nav id="menu" class="nav-main" role="navigation">
								<ul class="nav nav-main">
                                {% if request.session.campionato_id or request.session.profilo == 'League Admin' %}
									<li class="nav-active">
										<a href="{% url 'dashboard_index' %}">
											<i class="fa fa-home" aria-hidden="true"></i>
											<span>Dashboard</span>
										</a>
									</li>
									{% if request.session.profilo %}
									<!-- Gestione Squadra -->
									{% block menusquadra %} 
										{% include 'front/includes/base/menu-squadra.html' %}
									{% endblock %}
									<!-- END gestione squadra-->

									<!-- Gestione campionato -->
									{% block menucampionato %}
										{% include 'front/includes/base/menu-campionato.html' %}
									{% endblock %}
									<!-- END gestione campionato-->

									<!-- Gestione utenza (CA/LA) -->
									{% block menuutenza %}
										{% include 'front/includes/base/menu-utenza.html' %}
									{% endblock %}
									<!-- END gestione utenza-->
									{% endif %}
                                {% endif %}
								</ul>
							</nav>
						</div>
					</div>
				</aside>
{% endblock %}

app/biaset/templates/front/includes/base/vendor.html
{% load static %}
<!-- Vendor -->
		<script src="{% static 'assets/vendor/jquery/jquery.js' %}"></script>
		<script src="{% static 'assets/vendor/jquery-browser-mobile/jquery.browser.mobile.js' %}"></script>
		<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.js' %}"></script>
		<script src="{% static 'assets/vendor/nanoscroller/nanoscroller.js' %}"></script>
		<script src="{% static 'assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
		<script src="{% static 'assets/vendor/magnific-popup/magnific-popup.js' %}"></script>
		<script src="{% static 'assets/vendor/jquery-placeholder/jquery.placeholder.js' %}"></script>
		
		<!-- Specific Page Vendor -->
		<script src="{% static 'assets/vendor/jquery-ui/js/jquery-ui-1.10.4.custom.js' %}"></script>
		<script src="{% static 'assets/vendor/jquery-ui-touch-punch/jquery.ui.touch-punch.js' %}"></script>
		<script src="{% static 'assets/vendor/jquery-appear/jquery.appear.js' %}"></script>
		<script src="{% static 'assets/vendor/bootstrap-multiselect/bootstrap-multiselect.js' %}"></script>
		<script src="{% static 'assets/vendor/jquery-sparkline/jquery.sparkline.js' %}"></script>
		<script src="{% static 'assets/vendor/raphael/raphael.js' %}"></script>
		<script src="{% static 'assets/vendor/morris/morris.js' %}"></script>
		<script src="{% static 'assets/vendor/gauge/gauge.js' %}"></script>
		<script src="{% static 'assets/vendor/snap-svg/snap.svg.js' %}"></script>
		
		<!-- Theme Base, Components and Settings -->
		<script src="{% static 'assets/javascripts/theme.js' %}"></script>
		
		<!-- Theme Custom -->
		<script src="{% static 'assets/javascripts/theme.custom.js' %}"></script>
		
		<!-- Theme Initialization Files -->
		<script src="{% static 'assets/javascripts/theme.init.js' %}"></script>