app/biaset/biaset/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('', include('core.urls')),
    path('admin/doc/',include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')), # Django-Allauth URLs

]

app/biaset/core/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .views import HomeView, ShowCaseView, RegolamentoView

urlpatterns = [
    path('', ShowCaseView.as_view(), name='index'),
    path('regolamento/', RegolamentoView.as_view(),name='regolamento'),
    path('dashboard/', login_required(HomeView.as_view()), name='dashboard_index'),
    path('gestioneutenza/', include(('gestioneutenza.urls', 'gestioneutenza'), namespace='gestioneutenza')),
    path('gestionecampionato/', include(('gestionecampionato.urls', 'gestionecampionato'), namespace='gestionecampionato')),
    path('gestionesquadra/', include(('gestionesquadra.urls', 'gestionesquadra'), namespace='gestionesquadra')),
]

app/biaset/gestioneutenza/urls.py
from django.urls import path
from gestioneutenza.views import RegistrationView, StrategyRegistrationView, LoginView, InviteCreateView, LogoutView, ListUtentiView
from django.contrib.auth.decorators import login_required

app_name = 'gestioneutenza'
urlpatterns = [
    path('registrazione/', login_required(RegistrationView.as_view()), name='registrazione'),
    path('registrazione/<str:regtype>/', login_required(StrategyRegistrationView.as_view()), name='registrazione_ca'),
    path('login/', LoginView.as_view(), name='login_view'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('creainvito/', InviteCreateView.as_view(), name='crea_invito'),
    path('utenti/', login_required(ListUtentiView.as_view()), name='list_utenti')
]

app/biaset/gestioneutenza/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.base import ModelBase
from django.db.models.fields.related import ManyToManyField
from datetime import datetime
from gestionecampionato.models import Campionato
from django.core.exceptions import ValidationError

# Override del metodo __str__ del modello User predefinito
from django.contrib.auth.models import User


def get_utente(self):
    return f"{self.first_name} {self.last_name} [{self.username}]"


User.add_to_class("__str__", get_utente)


class Profilo(models.Model):
    nome = models.CharField(max_length=255, verbose_name='Tipo profilo')
    user = ManyToManyField(User, verbose_name='Utente', blank=True, related_name='profilo')

    class Meta:
        verbose_name_plural = "Profili"

    def __str__(self) -> str:
        return self.nome


class Invito(models.Model):
    user = models.ForeignKey(User, verbose_name="Creato da", on_delete=models.CASCADE)
    expire_dt = models.DateField(verbose_name="Data di scadenza (mm/gg/aaaa)")
    codice_invito = models.CharField(max_length=32)
    destinatario = models.EmailField(max_length=50, verbose_name="Email destinatario", unique=True)
    campionato = models.ForeignKey(Campionato, verbose_name='Campionato', on_delete=models.CASCADE, null=True,
                                   blank=True)

    def __str__(self) -> str:
        return f"{self.destinatario}, {self.codice_invito}"

    def clean(self):
        now = datetime.today().date()
        if self.expire_dt < now:
            raise ValidationError("L'invito deve avere una data di scadenza posteriore a quella odierna!",
                                  code='data-non-valida')

    class Meta:
        verbose_name_plural = 'Inviti'

app/biaset/gestioneutenza/forms.py
import random
from re import A
import string
from django import forms
from .models import Invito
from gestionecampionato.models import Campionato
from django.core.mail import send_mail
from datetime import datetime

class CreaInvitoForm(forms.ModelForm):
    
    class Meta:
        model = Invito
        fields = ('destinatario', 'expire_dt', 'user')
        widgets = {
            'destinatario': forms.EmailInput(attrs={'class': 'form-control'})
        }
        error_messages = {
            'data-non-valida': "L'invito deve avere una data di scadenza posteriore a quella odierna!"
        }
        
    def save(self, commit=True):
        instance = super().save(commit=False)
        # Prendo il campionato dall'utente
        campionato = Campionato.objects.filter(championship_admin=instance.user).first()
        instance.campionato = campionato
        # Genero il codice invito
        codice_invito = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(10))
        instance.codice_invito = codice_invito
        self.send_email_notification(campionato, instance.destinatario, codice_invito)
        if commit:
            instance.save()
        return instance
    
    def send_email_notification(self, campionato: Campionato, destinatario: str, codice_invito: str) -> None:
        send_mail(
        "BiaSet - Invito iscrizione",
        f"Ciao! Sei stato invitato a partecipare al campionato {campionato.nome_campionato} da {campionato.championship_admin.first_name}. "  
        f"\nIl codice di invito è {codice_invito}. Visita il nostro sito (http://woofz.dev) per completare la registrazione. Per la registrazione, " \
        f"dovrai usare il social corrispondente a questo indirizzo e-mail." \
        f"\n \n Lo staff di BiaSet.",
        f'biaset@woofz.dev', 
        [destinatario],
        fail_silently=True)

app/biaset/gestioneutenza/views.py
import logging

from django.contrib.auth.models import User
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic.base import View
from django.contrib import messages
from django.views.generic import CreateView, ListView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import sessions
from gestionesquadra.models import Squadra
from .models import Invito
from .forms import CreaInvitoForm
from .strategyclasses.strategy import Context, Strategy
from .strategyclasses.allenatorestrategy import AllenatoreStrategy
from .strategyclasses.castrategy import CaStrategy
from .strategyclasses.invitenotfound import InviteNotFoundException
from .models import Profilo
from django.contrib.auth import logout
from core.decorators import check_if_profile_exists, check_user_permission_ca
from django.utils.decorators import method_decorator

decorators_ca = [check_user_permission_ca]


class RegistrationView(View):
    """Definisce la vista di Registrazione"""
    template_name = "front/pages/gestioneutenza/registrazione.html"

    @method_decorator(check_if_profile_exists)
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, context={})


class StrategyRegistrationView(View):
    """Definisce la vista di registrazione tramite Strategy pattern"""
    error_template_name = "front/error.html"
    strategy_context = Context(CaStrategy())
    redir = 'gestionecampionato:inserisci_campionato'

    @method_decorator(check_if_profile_exists)
    def get(self, request, regtype: str):
        error = 'Invito non valido o non esistente.'
        if regtype == 'allenatore':
            self.strategy_context = Context(AllenatoreStrategy())
            self.redir = 'dashboard_index'
        utente = User.objects.get(pk=request.user.pk)
        try:
            if self.strategy_context.doOperation(utente):
                profilo = Profilo.objects.get(user=utente)
                request.session['profilo'] = profilo.nome
                messages.success(
                    request, 'Registrazione avvenuta con successo!')
                return redirect(reverse(self.redir))
        except InviteNotFoundException:
            pass

        return render(
            request,
            self.error_template_name,
            context={
                'error': error})


class LoginView(View):
    '''Definisce la login view'''
    template_name = "front/pages/gestioneutenza/login.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, context={})


class LogoutView(View):
    """Classe vista per funzionalità di logout"""

    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect(reverse('dashboard_index'))


@method_decorator(decorators_ca, name='dispatch')
class InviteCreateView(SuccessMessageMixin, CreateView):
    """Classe vista per la creazione di un invito"""
    model = Invito
    template_name = "front/pages/gestioneutenza/creainvito.html"
    form_class = CreaInvitoForm
    success_url = reverse_lazy('dashboard_index')
    success_message = 'Invito creato correttamente!'


@method_decorator(decorators_ca, name='dispatch')
class ListUtentiView(ListView):
    model = User
    template_name = "front/pages/gestioneutenza/list-utenti.html"
    usr = User.objects.select_related('squadra').all()

app/biaset/templates/front/pages/gestioneutenza/creainvito.html
{% extends 'front/base.html' %}

{% block content %}
<section role="main" class="content-body">
    <header class="page-header">
        <h2>Creazione invito</h2>
    </header>
        <div class="row">
            <div class="col-md-12">
                <section class="panel">
                    <header class="panel-heading">   
                        <h2 class="panel-title">Crea invito</h2>
                    </header>
                    <div class="panel-body">
                        <form class="form-horizontal form-bordered" action="" method="post">
                            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

                            {% csrf_token %}
                            {{ form.media }}
                            {{ form.destinatario.errors }}
                            {{form.non_field_errors}}
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="inputDefault" required>Destinatario</label>
                                <div class="col-md-6">
                                    {{ form.destinatario }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="inputDefault" required>Data scadenza invito (mm-gg-aaaa)</label>
                                <div class="col-md-6">
                                    <input type="text" data-plugin-datepicker="" id="{{ form.expire_dt.id_for_label }}" name="{{ form.expire_dt.name }}"
                                     class="form-control" required>
                                </div>
                            </div>
                            <input type="hidden" name="{{ form.user.name }}" value="{{ request.user.id }}">
        
                        
                    </div>
                    <footer class="panel-footer">
                        <input type="submit" id="submit" value="Crea invito" class="btn btn-primary"></button>
                    </footer>
                </form>
                </section>
</section>

{% endblock %}

app/biaset/templates/front/pages/gestioneutenza/email.html
<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
        <h1>{{ user_name }}</h1>
        <h2>{{ subject }}</h2>
    </body>
</html>

app/biaset/templates/front/pages/gestioneutenza/list-utenti.html
{% extends "front/base.html" %}

{% block content %}
<div class=""
    <h2>Utenti</h2>
    <ul>
        {% for publisher in object_list %}
            <li>{{ publisher.name }}</li>
        {% endfor %}
    </ul>
    <section role="main" class="content-body">
        <header class="page-header">
            <h2>Lista utenti</h2>
        </header>
            <div class="row">
                <div class="col-md-12">
                    <section class="panel">
                        <header class="panel-heading">
                            <h2 class="panel-title">Utenti</h2>
                        </header>
                        <div class="panel-body">
                            <p>Di seguito una lista degli utenti iscritti alla piattaforma</p>
                            <div class="col-md-6">
                                <div class="table-responsive">
                                <table class="table table-hover mb-none">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Nome</th>
                                            <th>Cognome</th>
                                            <th>Campionato</th>
                                            <th>Squadra</th>
                                            <th>Cancella</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for utente in object_list %}
                                        <tr>
                                            <td>{{ utente.id }}</td>
                                            <td>{{ utente.first_name }}</td>
                                            <td>{{ utente.last_name }}</td>
                                            <td>{{ utente.squadra.campionato }}</td>
                                            <td>{{ utente.squadra.nome }}</td>
                                            <td></td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </section>
                </div>
                </section>
            </div>
        </div>
    </section>
{% endblock %}

app/biaset/templates/front/pages/gestioneutenza/login.html
{% load static %}
{% load socialaccount %}
{% providers_media_js %}

<!doctype html>
<html class="fixed">
	<head>

		<!-- Basic -->
		<meta charset="UTF-8">

		<meta name="keywords" content="VQ Business Manager Login" />
		<meta name="description" content="Login">
		<meta name="author" content="w00fz">
		<title>BiaSet Login</title>
		<!-- Mobile Metas -->
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

		<!-- Web Fonts  -->
		<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">

		<!-- Vendor CSS -->
		<link rel="stylesheet" href="{% static 'assets/vendor/bootstrap/css/bootstrap.css' %}" />
		<link rel="stylesheet" href="{% static 'assets/vendor/font-awesome/css/font-awesome.css' %}" />
		<link rel="stylesheet" href="{% static 'assets/vendor/magnific-popup/magnific-popup.css' %}" />
		<link rel="stylesheet" href="{% static 'assets/vendor/bootstrap-datepicker/css/datepicker3.css' %}" />

		<!-- Theme CSS -->
		<link rel="stylesheet" href="{% static 'assets/stylesheets/theme.css' %}" />

		<!-- Skin CSS -->
		<link rel="stylesheet" href="{% static 'assets/stylesheets/skins/default.css' %}" />

		<!-- Theme Custom CSS -->
		<link rel="stylesheet" href="{% static 'assets/stylesheets/theme-custom.css' %}">

		<!-- Head Libs -->
		<script src="{% static 'assets/vendor/modernizr/modernizr.js' %}"></script>


		<!-- Icons -->
		<script src="https://kit.fontawesome.com/283b224be3.js" crossorigin="anonymous"></script>

	</head>
	<body>
		<!-- start: page -->
		<section class="body-sign">
			<div class="center-sign">
				<a href="/" class="logo pull-left">
					<img src="{% static 'assets/images/logo_fca.png' %}"  alt="Porto Admin" />
				</a>

				<div class="panel panel-sign">
					<div class="panel-title-sign mt-xl text-right">
						<h2 class="title text-uppercase text-bold m-none"><i class="fa fa-user mr-xs"></i> LOGIN</h2>
					</div>
					<div class="panel-body">
						<form action="index.html" method="post">
						<p class="center"><strong>Seleziona un Social col quale effettuare il login</strong></p>
							<div class="mb-xs text-center">
								<a href="{% provider_login_url "google" %}" class="btn btn-primary mb-md ml-xs mr-xs">Login con Google <i class="fab fa-google"></i></a>
								
								<a href="{% provider_login_url "facebook" method="js_sdk" %}" class="btn btn-facebook mb-md ml-xs mr-xs">Login con Facebook<i class="fab fa-facebook"></i></a>
                                <a><a href="{% url 'admin:index' %}">Login League Admin</a></p>
							</div>
						</form>
					</div>
				</div>
				<p class="text-center text-muted mt-md mb-md">Developed by <a href="mailto:danilo.aliberti@woofz.net">w00fz</a></p>
			</div>
		</section>
		<!-- end: page -->

		<!-- Vendor -->
		<script src="{% static 'assets/vendor/jquery/jquery.js' %}"></script>
		<script src="{% static 'assets/vendor/jquery-browser-mobile/jquery.browser.mobile.js' %}"></script>
		<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.js' %}"></script>
		<script src="{% static 'assets/vendor/nanoscroller/nanoscroller.js' %}"></script>
		<script src="{% static 'assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
		<script src="{% static 'assets/vendor/magnific-popup/magnific-popup.js' %}"></script>
		<script src="{% static 'assets/vendor/jquery-placeholder/jquery.placeholder.js' %}"></script>
		
		<!-- Theme Base, Components and Settings -->
		<script src="{% static 'assets/javascripts/theme.js' %}"></script>
		
		<!-- Theme Custom -->
		<script src="{% static 'assets/javascripts/theme.custom.js' %}"></script>
		
		<!-- Theme Initialization Files -->
		<script src="{% static 'assets/javascripts/theme.init.js' %}"></script>

	</body>
</html>

app/biaset/templates/front/pages/gestioneutenza/registrazione.html
{% extends 'front/base.html' %}

{% block content %}
<section role="main" class="content-body">
    <header class="page-header">
        <h2>Iscrizione al portale</h2>
    </header>
        <div class="row">
            <div class="col-md-12">
                <section class="panel">
                    <header class="panel-heading">
                        <h2 class="panel-title">Iscrizione</h2>
                    </header>
                    <div class="panel-body">
                        <p class="text-justify"><h4>Benvenuto su <strong>Biaset</strong>! <br> <br> Se sei stato invitato da un amministratore di campionato, clicca su <strong>Partecipa a campionato</strong> per utilizzare l'invito per l'iscrizione al campionato! <br>In alternativa, se vuoi creare il tuo campionato di Fantacalcio, clicca su <strong>Crea campionato.<strong></h4></p>
                        <div class="panel-body col-m-8 center">
                            <div class="btn-group btn-group-justified">
                                <a href="{% url 'gestioneutenza:registrazione_ca' 'ca' %}" class="btn btn-danger" role="button"><b>Crea campionato</b></a>
                                <a href="{% url 'gestioneutenza:registrazione_ca' 'allenatore' %}" class="btn btn-success" role="button"><b>Partecipa a campionato</b></a>
                            </div>
                            <br>
                        </div>
                    </div>
                </section>
            </div>
            </section>
        </div>
    </div>
</section>
{% endblock content %}