app/biaset/biaset/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('', include('core.urls')),
    path('admin/doc/',include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')), # Django-Allauth URLs

]

app/biaset/core/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .views import HomeView, ShowCaseView, RegolamentoView

urlpatterns = [
    path('', ShowCaseView.as_view(), name='index'),
    path('regolamento/', RegolamentoView.as_view(),name='regolamento'),
    path('dashboard/', login_required(HomeView.as_view()), name='dashboard_index'),
    path('gestioneutenza/', include(('gestioneutenza.urls', 'gestioneutenza'), namespace='gestioneutenza')),
    path('gestionecampionato/', include(('gestionecampionato.urls', 'gestionecampionato'), namespace='gestionecampionato')),
    path('gestionesquadra/', include(('gestionesquadra.urls', 'gestionesquadra'), namespace='gestionesquadra')),
]

app/biaset/gestionesquadra/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import VisualizzaSquadraView, AssociaGiocatoreASquadra, licenziaGiocatore, InserisciSquadraView, \
    VisualizzaSquadreLAView, ModificaNomeSquadraView, ModificaSquadraView, eliminaSquadra

app_name = 'gestionesquadra'
urlpatterns = [
    path('visualizzasquadra/<int:pk>/', login_required(VisualizzaSquadraView.as_view()), name='visualizza_squadra'),
    path('ajax/licenziagiocatore/', login_required(licenziaGiocatore), name='licenzia_giocatore_ajax'),
    path('ajax/eliminasquadra/', login_required(eliminaSquadra), name='elimina_squadra_ajax'),
    path('associagiocatore/', login_required(AssociaGiocatoreASquadra.as_view()), name='associa_giocatore'),
    path('inseriscisquadra/', login_required(InserisciSquadraView.as_view()), name='inserisci_squadra'),
    path('modificanomesquadra/<pk>/', login_required(ModificaNomeSquadraView.as_view()), name='modifica_squadra'),
    path('modificasquadra/<pk>/', login_required(ModificaSquadraView.as_view()), name='modifica_squadra_superuser'),
    path('list/', login_required(VisualizzaSquadreLAView.as_view()), name='visualizza_squadre'),
]

app/biaset/gestionesquadra/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.contrib.auth.models import User


class Squadra(models.Model):
    nome = models.CharField(max_length=50, verbose_name="Nome squadra", unique=True, validators=[
        RegexValidator(
            regex='^[A-Za-z a-z 0-9]*$',
            message='Il nome della squadra deve essere alfanumerico.',
            code='invalid_squadra'
        ),
    ])
    campionato = models.ForeignKey('gestionecampionato.Campionato', verbose_name="Campionato", on_delete=models.CASCADE)
    allenatore = models.OneToOneField(User, on_delete=models.SET_NULL, verbose_name='Allenatore', blank=True, null=True, related_name='squadra')
    
    def __str__(self):
        return f"{self.nome}"
    
    class Meta:
        verbose_name_plural = 'Squadre'


class Giocatore(models.Model):
    PLAYER_ROLES = [
        ('P', 'Portiere'), 
        ('D', 'Difensore'), 
        ('C', 'Centrocampista'), 
        ('A', 'Attaccante')
    ]
    nome_completo = models.CharField(max_length=255, blank=True, null=True, verbose_name='Cognome')
    ruolo = models.CharField(
        max_length=1,
        choices=PLAYER_ROLES,
        default='T',
        verbose_name='Ruolo',
        blank=True,
        null=True
    )
    id_voti = models.IntegerField(verbose_name='ID Voti Fantacalcio.it')
    quotazione = models.IntegerField(verbose_name='Quotazione', default=0)
    squadra = models.ManyToManyField(Squadra)
    
    def __str__(self) -> str: 
        return f"{self.nome_completo} [{self.ruolo}]"
    
    class Meta:
        verbose_name_plural = 'Giocatori'

app/biaset/gestionesquadra/forms.py
from django import forms
from django.contrib.auth.models import User

from gestionecampionato.models import Campionato
from .models import Giocatore, Squadra


class AssociaGiocatoreForm(forms.Form):
    """Form di associazione di un giocatore ad una squadra"""
    giocatore = forms.ModelChoiceField(queryset=Giocatore.objects.none(), required=True)
    squadra = forms.ModelChoiceField(queryset=Squadra.objects.none(), required=True)
    
    def __init__(self, *args, **kwargs):
        campionato = kwargs.pop('campionato', None)
        #squadra = kwargs.pop('squadra', None)

        super(AssociaGiocatoreForm, self).__init__(*args, **kwargs)
        self.fields['giocatore'].queryset = Giocatore.objects.all().exclude(squadra__campionato=campionato)
        self.fields['squadra'].queryset = Squadra.objects.filter(campionato=campionato)
        
    def associaGiocatore(self):
        cd = self.cleaned_data
        giocatore = Giocatore.objects.get(pk=cd['giocatore'].id)
        squadra = Squadra.objects.get(pk=cd['squadra'].id)
        giocatore.squadra.add(squadra)


class InserisciSquadraForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        profile = kwargs.pop('profile', None)
        user = kwargs.pop('user', None)
        super(InserisciSquadraForm, self).__init__(*args, **kwargs)

        if profile == 'Championship Admin':
            self.fields['campionato'].queryset = Campionato.objects.filter(championship_admin=user).all()
            self.fields['allenatore'].queryset = User.objects.all()

    class Meta:
        model = Squadra
        fields = '__all__'
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 60}),
        }

app/biaset/gestionesquadra/views.py
from multiprocessing import context
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View
from django.db.models import Sum
from django.views.generic import ListView, UpdateView
from .models import Squadra, Giocatore
from .forms import AssociaGiocatoreForm, InserisciSquadraForm
from django.contrib import sessions
from django.contrib import messages
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.views.generic.edit import FormView, CreateView
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.contrib import messages
from gestionecampionato.models import Campionato
from core.decorators import check_user_permission_ca, check_team_belonging, check_user_permission_la_ca, \
    check_user_permission_la, check_if_user_is_allenatore_squadra, check_partecipants, handle_view_exception
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.messages.views import SuccessMessageMixin

decorator_la = check_user_permission_la
decorator_la_ca = [check_user_permission_la_ca, handle_view_exception]
decorators_la = [decorator_la, handle_view_exception]
decorators_ca = [check_user_permission_ca, handle_view_exception]


@check_team_belonging
def licenziaGiocatore(request):
    '''Licenzia un giocatore da una squadra [AJAX Function]'''
    giocatore_id = request.GET.get('giocatore_id', None)
    squadra_id = request.GET.get('squadra_id', None)
    data = {
        'status': 'ok'
    }
    try:
        giocatore = Giocatore.objects.get(pk=giocatore_id)
        squadra = Squadra.objects.get(pk=squadra_id)
        giocatore.squadra.remove(squadra)
    except Exception:
        messages.error(request, 'Il giocatore in questione non è registrato.')
    return JsonResponse(data)


@check_team_belonging
def eliminaSquadra(request):
    '''Elimina una squadra [AJAX Function]'''
    squadra_id = request.GET.get('squadra_id', None)
    data = {
        'status': 'ok'
    }
    try:
        squadra = Squadra.objects.get(pk=squadra_id)
        squadra.delete()
    except Exception:
        messages.error(request, 'La squadra non esiste.')
    return JsonResponse(data)


def check_squadra_ownership(request, pk: int, *args, **kwargs) -> bool:
    user = User.objects.get(pk=request.user.id)
    squadra_passata = Squadra.objects.get(pk=pk)
    if (user != squadra_passata.allenatore and request.session.get('profilo') not in ('League Admin', 'Championship Admin') 
        or int(request.session.get('campionato_id')) != int(squadra_passata.campionato.id)):
        return False
    return True
    

@method_decorator(handle_view_exception, name='dispatch')
class VisualizzaSquadraView(View):
    """Vista per la visualizzazione di una Squadra"""
    template_name = 'front/pages/gestionesquadra/list.html'
    
    def get(self, request, pk: int, *args, **kwargs):
        squadra = Squadra.objects.get(pk=pk)
        budget_disponibile = 0
        spesa_stipendi = 0
        ownership = False
        try:
            qs = Giocatore.objects.filter(squadra__id=squadra.pk).order_by('-ruolo', '-quotazione')
            stipendi = qs.aggregate(totale_quotazioni=Sum('quotazione'))
            budget_disponibile = 0 or round((50 - (stipendi['totale_quotazioni']/40))*3.14, 2)
            ownership = check_squadra_ownership(request=request, pk=pk)
            spesa_stipendi = round(stipendi['totale_quotazioni']/40, 2)
        except Exception:
            pass
        return render(request, self.template_name, context={'giocatori': qs, 'budget_disponibile': budget_disponibile,
                                                            'stipendi': spesa_stipendi, 
                                                            'ownership': ownership, 
                                                            'squadra': squadra})

@method_decorator(decorators_ca, name='dispatch')
class AssociaGiocatoreASquadra(FormView):
    """Vista di associazione giocatore a squadra"""
    template_name = 'front/pages/gestionesquadra/associa-giocatore.html'

    def get(self, request, *args, **kwargs):
        campionato = Campionato.objects.get(pk=request.session.get('campionato_id'))
        if Squadra.objects.filter(campionato__id=campionato.id).exists():
            form = AssociaGiocatoreForm(campionato=campionato)
        else:
            messages.error(request, 'Non ci sono squadre registrate al campionato!')
            return redirect('dashboard_index')

        return render(request, self.template_name, context={'form': form})

    def post(self, request, *args, **kwargs):
        campionato = Campionato.objects.get(pk=request.session.get('campionato_id'))
        form = AssociaGiocatoreForm(request.POST, campionato=campionato)

        if form.is_valid():
            form.associaGiocatore()
            messages.success(request, 'Giocatore associato correttamente!')
            return redirect('gestionesquadra:associa_giocatore')

        return render(request, self.template_name, context={'form': form})


@method_decorator(decorator_la_ca, name='dispatch')
@method_decorator(check_partecipants, name='dispatch')
class InserisciSquadraView(SuccessMessageMixin, CreateView):
    """Vista di inserimento squadra per LA"""
    model = Squadra
    template_name = 'front/pages/gestionesquadra/inserisci-squadra.html'
    form_class = InserisciSquadraForm
    success_url = reverse_lazy('dashboard_index')
    success_message = 'Squadra creata con successo!'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            'user': self.request.user,
            'profile': self.request.session.get('profilo')
        })
        return kwargs


@method_decorator(decorators_la, name='dispatch')
class VisualizzaSquadreLAView(ListView):
    """Vista di visualizzazione lista squadre per LA"""
    model = Squadra
    template_name = 'front/pages/gestionesquadra/visualizza-squadre.html'


@method_decorator(check_if_user_is_allenatore_squadra, name='dispatch')
@method_decorator(handle_view_exception, name='dispatch')
class ModificaNomeSquadraView(SuccessMessageMixin, UpdateView):
    success_url = reverse_lazy('dashboard_index')
    success_message = 'Nome modificato correttamente!'
    model = Squadra
    fields = ['nome']
    template_name = 'front/pages/gestionesquadra/modifica-squadra.html'


@method_decorator(decorator_la_ca, name='dispatch')
class ModificaSquadraView(SuccessMessageMixin, UpdateView):
    """Vista di inserimento squadra per LA"""
    model = Squadra
    template_name = 'front/pages/gestionesquadra/modifica-squadra.html'
    form_class = InserisciSquadraForm
    success_url = reverse_lazy('dashboard_index')
    success_message = 'Squadra modificata con successo!'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            'user': self.request.user,
            'profile': self.request.session.get('profilo'),
        })
        return kwargs

app/biaset/templates/front/pages/gestionesquadra/associa-giocatore.html
{% extends 'front/base.html' %}

{% block content %}
<section role="main" class="content-body">
    <header class="page-header">
        <h2>Associa giocatore a squadra</h2>
    </header>
        <div class="row">
            <div class="col-md-12">
                <section class="panel">
                    <header class="panel-heading">   
                        <h2 class="panel-title">Associa giocatore</h2>
                    </header>
                    <div class="panel-body">
                        <p class="center">Seleziona il giocatore e la squadra di destinazione.</p>
                        <form class="form-horizontal form-bordered" action="" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="text-danger">{{ form.errors }}</div>
                                <label class="col-md-3 control-label" for="inputDefault" required>Giocatore</label>
                                <div class="col-md-2">
                                    {{ form.giocatore }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="inputDefault" required>Squadra di destinazione</label>
                                <div class="col-md-6">
                                    {{ form.squadra }}
                                </div>
                            </div>                       
                    </div>
                    <footer class="panel-footer center">
                        <input type="submit" id="submit" value="Associa" class="btn btn-primary"></button>
                    </footer>
                </form>
                </section>
</section>

{% endblock %}

app/biaset/templates/front/pages/gestionesquadra/inserisci-squadra-ca.html
{% extends 'front/base.html' %}

{% block content %}
<section role="main" class="content-body">
    <header class="page-header">
        <h2>Inserisci squadra</h2>
    </header>
        <div class="row">
            <div class="col-md-12">
                <section class="panel">
                    <header class="panel-heading">
                        <h2 class="panel-title">Inserisci squadra</h2>
                    </header>
                    <div class="panel-body">
                        <p class="center">Compila i campi per inserire una nuova squadra.</p>
                        <form class="form-horizontal form-bordered" action="" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="text-danger">{{ form.errors }}</div>
                                <label class="col-md-3 control-label" for="inputDefault" required>Nome squadra</label>
                                <div class="col-md-2">
                                    {{ form.nome }}
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-6 hidden">
                                    {{ form.campionato }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="inputDefault" required>Allenatore</label>
                                <div class="col-md-6">
                                    {{ form.allenatore }}
                                </div>
                            </div>
                    </div>
                    <footer class="panel-footer center">
                        <input type="submit" id="submit" value="Inserisci squadra" class="btn btn-primary"></button>
                    </footer>
                </form>
                </section>
</section>

{% endblock %}

app/biaset/templates/front/pages/gestionesquadra/inserisci-squadra.html
{% extends 'front/base.html' %}

{% block content %}
<section role="main" class="content-body">
    <header class="page-header">
        <h2>Inserisci squadra</h2>
    </header>
        <div class="row">
            <div class="col-md-12">
                <section class="panel">
                    <header class="panel-heading">
                        <h2 class="panel-title">Inserisci squadra</h2>
                    </header>
                    <div class="panel-body">
                        <p class="center">Compila i campi per inserire una nuova squadra.</p>
                        <form class="form-horizontal form-bordered" action="" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="text-danger">{{ form.nome.errors }}</div>
                                <div class="text-danger">{{ form.campionato.errors }}</div>
                                <div class="text-danger">{{ form.allenatore.errors }}</div>
                                <label class="col-md-3 control-label" for="inputDefault" required>Nome squadra</label>
                                <div class="col-md-2">
                                    {{ form.nome }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="inputDefault" required>Campionato</label>
                                <div class="col-md-6">
                                    {{ form.campionato }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="inputDefault" required>Allenatore</label>
                                <div class="col-md-6">
                                    {{ form.allenatore }}
                                </div>
                            </div>
                    </div>
                    <footer class="panel-footer center">
                        <input type="submit" id="submit" value="Inserisci squadra" class="btn btn-primary"></button>
                    </footer>
                </form>
                </section>
</section>

{% endblock %}

app/biaset/templates/front/pages/gestionesquadra/list.html
{% extends "front/base.html" %}
{% block content %}

{% block javascripts %}
<script>
    
    $(document).ready(function(){
        $('.licenzia').click(function(){
            let team_id = $(this).val();
                   Swal.fire({
                      title: 'Conferma',
                      text: "Sei sicuro di voler licenziare il giocatore?",
                      icon: 'warning',
                      showCancelButton: true,
                      confirmButtonColor: '#3085d6',
                      cancelButtonColor: '#d33',
                      confirmButtonText: 'Si'
                    }).then((result) => {
                      if (result.isConfirmed) {
                          $.ajax({
                            url: '{% url 'gestionesquadra:licenzia_giocatore_ajax' %}',
                            data: {
                              'giocatore_id': $(this).val(),
                              'squadra_id': {{ squadra.id }},
                            },
                            dataType: 'json',
                            success: function(data) {
                                Swal.fire(
                                    'Licenziato!',
                                    'Il giocatore è stato licenziato!.',
                                    'success'
                                );
                                $('#'+team_id).closest("tr").hide();
                            }
                          });
                      }
                   });
            });
        });
</script>
{% endblock javascripts %}
    <section role="main" class="content-body">
        <header class="page-header">
            <h2>Visualizza squadra</h2>
        </header>
            <div class="row">
                <div class="col-md-12">
                    <section class="panel">
                        <header class="panel-heading">
                            <h2 class="panel-title">{{ squadra.nome }}</h2>
                        </header>
                        <div class="panel-body">
                            <p>Di seguito è listata la lista dei giocatori della squadra. Nel caso in cui fossi il proprietario, potrai licenziare qualsiasi giocatore tu voglia.</p>
                            <div class="col-md-6">
                                <div class="table-responsive">
                                <table class="table table-hover mb-none">
                                    <thead>
                                        <tr>
                                            <th>Nome Completo</th>
                                            <th>Ruolo</th>
                                            <th>Quotazione</th>
                                            {% if ownership %}<th>Licenzia</th>{% endif %}
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for giocatore in giocatori %}
                                        <tr id="{{ giocatore.id }}">
                                            <td>{{ giocatore.nome_completo }}</td>
                                            <td>{{ giocatore.ruolo }}</td>
                                            <td>{{ giocatore.quotazione }}</td>
                                            {% if ownership %}<td><button value="{{ giocatore.id }}" class="mb-xs mt-xs mr-xs btn btn-danger licenzia"><i class="fas fa-minus-circle"></i></button></td>{% endif %}
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            
                        </div>
                        <div class="col-md-6">
                            <section class="panel panel-featured-left panel-featured-secondary">
											<div class="panel-body">
												<div class="widget-summary">
													<div class="widget-summary-col widget-summary-col-icon">
														<div class="summary-icon bg-secondary">
															<i class="fa fa-usd"></i>
														</div>
													</div>
													<div class="widget-summary-col">
														<div class="summary">
															<h4 class="title">Stipendi da pagare</h4>
															<div class="info">
																<strong class="amount">{{ stipendi }} MILIONI DI EURO</strong>
															</div>
														</div>
                                                        <div class="summary-footer">
                                                            <a class="text-muted text-uppercase">Il calcolo è dato dalla somma totale delle quotazioni/40</a>
                                                        </div>
													</div>

												</div>
											</div>
										</section>
                    </section>
                </div>
                </section>
            </div>
        </div>
    </section>
{% endblock content %}

app/biaset/templates/front/pages/gestionesquadra/modifica-squadra.html
{% extends 'front/base.html' %}

{% block content %}
<section role="main" class="content-body">
    <header class="page-header">
        <h2>Modifica Squadra</h2>
    </header>
        <div class="row">
            <div class="col-md-12">
                <section class="panel">
                    <header class="panel-heading">
                        <h2 class="panel-title">Modifica Squadra</h2>
                    </header>
                    <div class="panel-body">
                        <form class="form-horizontal form-bordered" action="" method="post">
                            {% csrf_token %}
                            {{ form.media }}
                            <div class="form-group">
                                <div class="text-danger">{{ form.non_field_errors }}</div>
                                <label class="col-md-3 control-label" for="inputDefault" required>Nome squadra</label>
                                <div class="col-md-6">
                                    {{ form.nome }}
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-6 hidden">
                                    {{ form.campionato }}
                                </div>
                            </div>
                            {% if request.session.profilo != 'Allenatore'  %}
                                <div class="text-danger">{{ form.errors }}</div>
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="inputDefault" required>Allenatore</label>
                                <div class="col-md-6">
                                    {{ form.allenatore }}
                                </div>
                            </div>

                            {% endif %}
                    </div>
                    <footer class="panel-footer">
                        <input type="submit" id="submit" value="Modifica" class="btn btn-primary"></button>
                    </footer>
                </form>
                </section>
</section>

{% endblock %}

app/biaset/templates/front/pages/gestionesquadra/visualizza-squadre.html
{% extends "front/base.html" %}
{% block content %}
    <section role="main" class="content-body">
        <header class="page-header">
            <h2>Lista squadre</h2>
        </header>
            <div class="row">
                <div class="col-md-12">
                    <section class="panel">
                        <header class="panel-heading">
                            <h2 class="panel-title">Squadre partecipanti</h2>
                        </header>
                        <div class="panel-body">
                            <p>Di seguito una lista delle squadre presenti in piattaforma</p>
                            <div class="col-md-6">
                                <div class="table-responsive">
                                <table class="table table-hover mb-none">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Nome squadra</th>
                                            <th>Campionato</th>
                                            <th>Allenatore</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for squadra in object_list %}
                                        <tr>
                                            <td>{{ squadra.id }}</td>
                                            <td>{{ squadra.nome }}</td>
                                            <td>{{ squadra.campionato }}</td>
                                            <td>{{ squadra.allenatore }}</td>
                                            <td></td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </section>
                </div>
                </section>
            </div>
        </div>
    </section>
{% endblock %}