app/biaset/biaset/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('', include('core.urls')),
    path('admin/doc/',include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')), # Django-Allauth URLs

]

app/biaset/core/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .views import HomeView, ShowCaseView, RegolamentoView

urlpatterns = [
    path('', ShowCaseView.as_view(), name='index'),
    path('regolamento/', RegolamentoView.as_view(),name='regolamento'),
    path('dashboard/', login_required(HomeView.as_view()), name='dashboard_index'),
    path('gestioneutenza/', include(('gestioneutenza.urls', 'gestioneutenza'), namespace='gestioneutenza')),
    path('gestionecampionato/', include(('gestionecampionato.urls', 'gestionecampionato'), namespace='gestionecampionato')),
    path('gestionesquadra/', include(('gestionesquadra.urls', 'gestionesquadra'), namespace='gestionesquadra')),
]

app/biaset/gestionecampionato/urls.py
from django.urls import path, include
from .views import CreaCampionatoView, InserisciRiserveView, ModificaCampionatoView, VisualizzaPartitaView, \
    GeneraCalendarioView, SelezionaModuloView, InserisciFormazioneTitolariView, VisualizzaCalendarioView, \
    CaricamentoVotiView, CreaCampionatoLAView
from django.contrib.auth.decorators import login_required

app_name = 'gestionecampionato'

urlpatterns = [
    path('creacampionato/', login_required(CreaCampionatoView.as_view()), name='inserisci_campionato'),
    path('creacampionato/la/', login_required(CreaCampionatoLAView.as_view()), name='inserisci_campionato_la'),
    path('modificacampionato/<pk>/', login_required(ModificaCampionatoView.as_view()), name='modifica_campionato'),
    path('generacalendario/', login_required(GeneraCalendarioView.as_view()), name='genera_calendario'),
    path('inserisciformazione/', login_required(SelezionaModuloView.as_view()), name='seleziona_modulo'),
    path('inserisciformazione/titolari/<int:d>/<int:c>/<int:a>/',
         login_required(InserisciFormazioneTitolariView.as_view()), name='inserisci_titolari'),
    path('inserisciformazione/riserve/', login_required(InserisciRiserveView.as_view()), name='inserisci_riserve'),
    path('calendario/list/', login_required(VisualizzaCalendarioView.as_view()), name='visualizza_calendario'),
    path('visualizzapartita/<giornata>/<squadra_id>/', login_required(VisualizzaPartitaView.as_view()),
         name='visualizza_partita'),
    path('caricamentovoti/', login_required(CaricamentoVotiView.as_view()), name='caricamento_voti')
]

app/biaset/gestionesquadra/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import VisualizzaSquadraView, AssociaGiocatoreASquadra, licenziaGiocatore, InserisciSquadraView, \
    VisualizzaSquadreLAView, ModificaNomeSquadraView, ModificaSquadraView, eliminaSquadra

app_name = 'gestionesquadra'
urlpatterns = [
    path('visualizzasquadra/<int:pk>/', login_required(VisualizzaSquadraView.as_view()), name='visualizza_squadra'),
    path('ajax/licenziagiocatore/', login_required(licenziaGiocatore), name='licenzia_giocatore_ajax'),
    path('ajax/eliminasquadra/', login_required(eliminaSquadra), name='elimina_squadra_ajax'),
    path('associagiocatore/', login_required(AssociaGiocatoreASquadra.as_view()), name='associa_giocatore'),
    path('inseriscisquadra/', login_required(InserisciSquadraView.as_view()), name='inserisci_squadra'),
    path('modificanomesquadra/<pk>/', login_required(ModificaNomeSquadraView.as_view()), name='modifica_squadra'),
    path('modificasquadra/<pk>/', login_required(ModificaSquadraView.as_view()), name='modifica_squadra_superuser'),
    path('list/', login_required(VisualizzaSquadreLAView.as_view()), name='visualizza_squadre'),
]

app/biaset/templates/front/pages/dashboard-index.html
{% extends 'front/base.html' %}
{% block content %}

{% if request.session.profilo != 'Allenatore' %}
{% block javascripts %}
<script>

    $(document).ready(function(){
        $('.eliminaSquadra').click(function(){
            let team_id = $(this).attr('id');
                   Swal.fire({
                      title: 'Conferma',
                      text: "Sei sicuro di voler eliminare la squadra?",
                      icon: 'warning',
                      showCancelButton: true,
                      confirmButtonColor: '#3085d6',
                      cancelButtonColor: '#d33',
                      confirmButtonText: 'Si'
                    }).then((result) => {
                      if (result.isConfirmed) {
                          $.ajax({
                            url: '{% url 'gestionesquadra:elimina_squadra_ajax' %}',
                            data: {
                              'squadra_id': team_id,
                              'requester_id': {{ request.user.id }}
                            },
                            dataType: 'json',
                            success: function(data) {
                                Swal.fire(
                                    'Eliminata!',
                                    'La squadra è stata eliminata!.',
                                    'success'
                                );
                                $('#'+team_id).closest("tr").hide();
                            }
                          });
                      }
                   });
            });
        });
</script>
{% endblock javascripts %}
{% endif %}

    {%  if request.session.profilo != 'League Admin' %}
				<section role="main" class="content-body">
					<header class="page-header">
						<h2>Dashboard</h2>
					</header>
						<div class="row">
							<div class="col-md-12">
								<section class="panel panel-primary">
									<header class="panel-heading">
										<h2 class="panel-title">Cos'è questo portale?</h2>
										<p class="panel-subtitle">Info generali su BiaSet</p>
									</header>
									<div class="panel-body">
										<p class="text-justify">Benvenuto sul portale <strong>BiaSet</strong>, portale creato da appassionati di Fantacalcio per appassionati di Fantacalcio! :)
                                        <br>Su questa piattaforma potrai creare il tuo campionato fantacalcistico basato su regole da noi create per rendere il gioco più divertente e competitivo. In alternativa, potrai partecipare ad un campionato previo invito.</p>
									</div>
								</section>
							</div>

						<div class="col-lg-4 col-md-12">
							<section class="panel">
								<header class="panel-heading">
									<h2 class="panel-title">Squadre del campionato</h2>
								</header>
								<div class="panel-body">
									<div class="table-responsive">
										<table class="table table-striped mb-none">
											<thead>
												<tr>
													<th>Nome squadra</th>
													<th>Allenatore</th>
                                                    {% if request.session.profilo != 'Allenatore' %}<th></th>{% endif %}
                                                    {% if request.session.profilo != 'Allenatore' %}<th></th>{% endif %}
												</tr>
											</thead>
											<tbody>
												{% for squadra in squadre %}
												<tr>
													<td><a href="{% url 'gestionesquadra:visualizza_squadra' squadra.id %}">{{ squadra.nome }}</a></td>
													<td><span class="label label-primary">{{ squadra.allenatore.first_name }} {{ squadra.allenatore.last_name }}</span></td>
                                                {% if request.session.profilo != 'Allenatore' %}<th><a href="{% url 'gestionesquadra:modifica_squadra_superuser' squadra.id %}"><i class="fas fa-edit"></i></a></th>{% endif %}
                                                {% if request.session.profilo != 'Allenatore' %}<th id="{{ squadra.id }}"><a href="#" class="eliminaSquadra" id="{{ squadra.id }}"><i class="fas fa-trash"></i></a></th>{% endif %}
												</tr>
												{% endfor %}
											</tbody>
										</table>
									</div>
								</div>
							</section>
						</div>
							<div class="col-md-6 col-lg-12 col-xl-6">
								<div class="row">
									<div class="col-md-12 col-lg-6 col-xl-8">
										<section class="panel panel-featured-left panel-featured-primary">
											<div class="panel-body">
												<div class="widget-summary">
													<div class="widget-summary-col widget-summary-col-icon">
														<div class="summary-icon bg-primary">
															<i class="fa fa-trophy"></i>
														</div>
													</div>
													<div class="widget-summary-col">
														<div class="summary">
															<h4 class="title">Campionato</h4>
															<div class="info">
																<strong class="amount">{{ request.session.nome_campionato }}</strong>
															</div>
                                                            <div class="summary-footer">
                                                                <a class="text-muted text-uppercase"># Partecipanti: {{ campionato.partecipanti }}</a>
                                                            </div>
														</div>
													</div>
												</div>
											</div>
										</section>
									</div>
                                    {% if request.session.squadra_id %}
									<div class="col-md-7 col-lg-7 col-xl-8">
										<section class="panel panel-featured-left panel-featured-danger">
											<div class="panel-body">
												<div class="widget-summary">
													<div class="widget-summary-col widget-summary-col-icon">
														<div class="summary-icon bg-danger">
															<i class="fas fa-futbol"></i>
														</div>
													</div>
													<div class="widget-summary-col">
														<div class="summary">
															<h4 class="title">Partita</h4>
															<div class="info">
																<a class="amount text-primary" href="{% url 'gestionecampionato:visualizza_partita' request.session.giornata_corrente request.session.squadra_id %}">{{ request.session.partita_corrente }}</a></strong>
															</div>
														</div>
                                                    <div class="summary-footer">
													    <a class="text-muted text-uppercase">Giornata numero {{ request.session.giornata_corrente }}</a>
    												</div>
													</div>
												</div>
											</div>
										</section>
									</div>
								</div>
						</div>
                        {% endif %}
					</div>
				</section>
    {% else %}
        {% include 'front/pages/dashboard-league-admin.html' %}
    {% endif %}
{% endblock %}

app/biaset/templates/front/pages/dashboard-league-admin.html
{% block content %}
<section role="main" class="content-body">
					<header class="page-header">
						<h2>Dashboard</h2>
					</header>
						<div class="row">
							<div class="col-md-12">
								<section class="panel panel-primary">
									<header class="panel-heading">
										<h2 class="panel-title">Cos'è questo portale?</h2>
										<p class="panel-subtitle">Info generali su BiaSet</p>
									</header>
									<div class="panel-body">
										<p class="text-justify">Benvenuto sul portale <strong>BiaSet</strong>, portale creato da appassionati di Fantacalcio per appassionati di Fantacalcio! :)
                                        <br>In qualità di <strong>League Admin</strong>, avrai la possibilità di visualizzare i dati relativi ai campionati, alle squadre, ecc. Inoltre, hai un accesso esclusivo all'Amministrazione del Framework. Clicca <a class="h4" href="{% url 'admin:index' %}">QUI</a> per accedervi. </p>
									</div>
								</section>
							</div>
                        </div>
						<div class="col-lg-3 col-md-12">
							<section class="panel">
								<header class="panel-heading">
									<h2 class="panel-title">Utenti della piattaforma</h2>
								</header>
								<div class="panel-body">
									<div class="table-responsive">
										<table class="table table-striped mb-none">
											<thead>
												<tr>
													<th>ID</th>
													<th>Nome</th>
													<th>Cognome</th>
													<th>Email</th>
												</tr>
											</thead>
											<tbody>
												{% for utente in dati_piattaforma.utenti %}
												<tr>
													<td>{{ utente.id }}</td>
													<td>{{ utente.first_name }}</td>
													<td>{{ utente.last_name }}</td>
													<td>{{ utente.email }}</td>
												</tr>
												{% endfor %}
											</tbody>
										</table>
									</div>
								</div>
							</section>
						</div>
						<div class="col-lg-3 col-md-12">
							<section class="panel">
								<header class="panel-heading">
									<h2 class="panel-title">Squadre della piattaforma</h2>
								</header>
								<div class="panel-body">
									<div class="table-responsive">
										<table class="table table-striped mb-none">
											<thead>
												<tr>
													<th>ID</th>
													<th>Nome</th>
													<th>Allenatore</th>
													<th>Campionato</th>
                                                    <th>Modifica</th>
												</tr>
											</thead>
											<tbody>
												{% for squadra in dati_piattaforma.squadre %}
												<tr>
													<td>{{ squadra.id }}</td>
													<td>{{ squadra.nome }}</td>
													<td>{{ squadra.allenatore }}</td>
													<td>{{ squadra.campionato }}</td>
                                                    <td></td>
												</tr>
												{% endfor %}
											</tbody>
										</table>
									</div>
								</div>
							</section>
						</div>
							<div class="col-md-6 col-lg-12 col-xl-6">
								<div class="row">
									<div class="col-md-12 col-lg-6 col-xl-8">
										<section class="panel panel-featured-left panel-featured-quartenary">
											<div class="panel-body">
												<div class="widget-summary">
													<div class="widget-summary-col widget-summary-col-icon">
														<div class="summary-icon bg-quartenary">
															<i class="fa fa-users"></i>
														</div>
													</div>
													<div class="widget-summary-col">
														<div class="summary">
															<h4 class="title">Numero iscritti</h4>
															<div class="info">
																<strong class="amount">{{ dati_piattaforma.n_utenti }}</strong>
															</div>
                                                            <div class="summary-footer">
                                                                <a class="text-muted text-uppercase">Include anche i Championship/League Admin</a>
                                                            </div>
														</div>
													</div>
												</div>
											</div>
										</section>
									</div>
									<div class="col-md-7 col-lg-7 col-xl-8">
										<section class="panel panel-featured-left panel-featured-primary">
											<div class="panel-body">
												<div class="widget-summary">
													<div class="widget-summary-col widget-summary-col-icon">
														<div class="summary-icon bg-primary">
															<i class="fas fa-trophy"></i>
														</div>
													</div>
													<div class="widget-summary-col">
														<div class="summary">
															<h4 class="title">Numero campionati</h4>
															<div class="info">
																<strong class="amount">{{ dati_piattaforma.n_campionati }}</strong>
															</div>
														</div>
													</div>
												</div>
											</div>
										</section>
									</div>
                                    <div class="col-md-7 col-lg-7 col-xl-8">
										<section class="panel panel-featured-left panel-featured-dark">
											<div class="panel-body">
												<div class="widget-summary">
													<div class="widget-summary-col widget-summary-col-icon">
														<div class="summary-icon bg-dark">
															<i class="fas fa-flag"></i>
														</div>
													</div>
													<div class="widget-summary-col">
														<div class="summary">
															<h4 class="title">Numero squadre</h4>
															<div class="info">
																<strong class="amount">{{ dati_piattaforma.n_squadre }}</strong>
															</div>
														</div>
													</div>
												</div>
											</div>
										</section>
									</div>
                                    <div class="col-md-7 col-lg-7 col-xl-8">
										<section class="panel panel-featured-left panel-featured-secondary">
											<div class="panel-body">
												<div class="widget-summary">
													<div class="widget-summary-col widget-summary-col-icon">
														<div class="summary-icon bg-secondary">
															<i class="fas fa-empire"></i>
														</div>
													</div>
													<div class="widget-summary-col">
														<div class="summary">
															<h4 class="title">Numero partite</h4>
															<div class="info">
																<strong class="amount">{{ dati_piattaforma.n_partite }}</strong>
															</div>
														</div>
													</div>
												</div>
											</div>
										</section>
									</div>
								</div>
								</div>
				</section>
{% endblock content %}